name: Build Android APK (frontend)

on:
  workflow_dispatch:
  push:
    paths:
      - '**'

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps (ci)
        run: npm ci --legacy-peer-deps

      - name: Build web bundle
        run: npm run build

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Capacitor Android sync/add
        run: |
          npx cap sync
          if [ ! -d android ]; then npx cap add android; fi

      - name: Build Android Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk


